# Generated by Django 4.2.2 on 2023-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание книги'),
        ),
    ]
